spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
  h2:
    console:
      enabled: true

management:
  security:
    enabled: false

logging:
  level:
    root: INFO
    com.khabaj.ekpir: DEBUG

