version: '3'
services:
  service-registry:
      build:
        context: ./service-registry
        args:
          - JAR_FILE=service-registry-0.0.1-SNAPSHOT.jar
      ports:
        - "8761:8761"
   gateway-service:
        build:
          context: ./service-registry
          args:
            - JAR_FILE=gateway-service-0.0.1-SNAPSHOT.jar
        ports:
          - "8000:8000"

  auth-service:
    build:
      context: ./auth-service
      args:
        - JAR_FILE=auth-service-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    depends_on:
      - service-registry


